name: Inject/Extract Cache
description: "Injects the cached data into the docker build(x|kit) process"
inputs:
  cache-map:
    required: true
    description: "The map of actions source paths to container destination paths or mount arguments"
  cache-source:
    deprecationMessage: "Use `cache-map` instead"
    description: "Where the cache is stored in the calling workspace. Default: `cache`"
  cache-target:
    deprecationMessage: "Use `cache-map` instead"
    description: "Where the cache is stored in the docker container. Default: `/root/.cache/go-build`"
  scratch-dir:
    default: scratch
    description: "Where the action is stores some temporary files for its processing. Default: `scratch`"
  skip-extraction:
    default: "false"
    description: "Skip the extraction of the cache from the docker container"
  save-always:
    default: "false"
    description: "Run the post step to save the cache even if another step before fails"
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'
  post-if: 'success() || github.event.inputs.save-always'
