#!/bin/bash
set -eux -o pipefail
: "Argv0: $0"
: "Prepare Timestamp for Layer Cache Busting"
date --iso=ns | tee "$(./read-action-input scratch-dir)"/buildstamp
: "Prepare Dancefile to Access Caches"
cat >"$(./read-action-input scratch-dir)"/Dancefile.extract <<EOF
FROM busybox:1
COPY buildstamp buildstamp
RUN --mount=type=cache,target="$(./read-action-input cache-target)" \
    mkdir -p /var/dance-cache/ \
    && cp -p -R "$(./read-action-input cache-target)"/. /var/dance-cache/ || true
EOF
cat "$(./read-action-input scratch-dir)"/Dancefile.extract
: "Extract Data into Docker Image"
docker buildx build -f "$(./read-action-input scratch-dir)"/Dancefile.extract --tag dance:extract --load "$(./read-action-input scratch-dir)"
: "Create Extraction Image"
docker rm -f cache-container && docker create -ti --name cache-container dance:extract
: "Unpack Docker Image into Scratch"
docker cp -L cache-container:/var/dance-cache - | tar -H posix -x -C "$(./read-action-input scratch-dir)"
: "Move Cache into Its Place"
sudo rm -rf "$(./read-action-input cache-source)"
mv "$(./read-action-input scratch-dir)"/dance-cache "$(./read-action-input cache-source)"
