#!/usr/bin/env bash
# helper script for printing kebab-cased env vars.
# e.g., "foo-bar" -> "INPUT_FOO-BAR".
set -eu -o pipefail 

arg=INPUT_${1^^}
while IFS= read -r -d '' var; do
  [[ $var = "$arg"=* ]] || continue
  echo "${var#"${arg}="}"
  break
done </proc/self/environ
